### ISSUE TITLE
ParseCloud trouble

### ISSUE THREAD

**Issue by Helten** [sidiabale/parse4cn1#19] opened 2016-06-23 21:14 UTC
I just upgraded to the latest release, and calls to ParseCloud.callFunction() are no longer working. In the network monitor I can see that the new version doesn't include "sessionToken=xxxxx" in the post body, as opposed to the old version. This results in a "TypeError: Cannot read property 'id' of null" when my cloud code tries to referene the current user. Am I missing something, or is this a bug?

**Comment by sidiabale** [comment] 2016-06-23 21:34
Hi, 

Parse Server cloud code no longer supports current user as explained here: https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse#no-current-user

That's most likely why your call is failing. Try removing the current user and see if it works. Then try the solution suggested on the aforementioned page.

**Comment by Helten** [comment] 2016-06-23 23:13
Hi,
thank you for the link. I seem to have some reading up to do. However, it still looks like something is missing from the Post requests. I was already using request.user in my Cloud code, so that wasn't the problem. When I manually add the header HEADER_SESSION_TOKEN to the ParsePostCommand before executing it, the cloud calls starts working again. The  "sessionToken=xxxxx" that I mentioned earlier, turned out to be a red herring. The issue is the missing header. Please correct me if I'm wrong.

Cheers, Yngve

**Comment by sidiabale** [comment] 2016-06-24 08:26
Hi, During the update I did indeed remove the session token headers because they were causing some calls to fail. With this information from you, I'll have a fresh look over the weekend and make the changes needed. Gladly, you have a workaround so you can proceed.

**Comment by sidiabale** [comment] 2016-06-29 03:58
Hi, I've reviewed this issue. In the pre-parse4cn1 v3.0, the base `ParseCommand` automatically added the session token header if it was present in the payload or if there was a current user logged in:

```
if (!data.has(ParseConstants.FIELD_SESSION_TOKEN) && ParseUser.getCurrent() != null) {
    data.put(ParseConstants.FIELD_SESSION_TOKEN, ParseUser.getCurrent().getSessionToken());
}

if (data.has(ParseConstants.FIELD_SESSION_TOKEN)) {
    headers.put(ParseConstants.HEADER_SESSION_TOKEN, data.getString(ParseConstants.FIELD_SESSION_TOKEN));
} 
```

However, doing that now results in an error: `{"code":107,"error":"invalid JSON"}`

So (cloud code) calls that require the session token must add it explicitly as you've done, e.g.

```
ParseCommand command;
// create command here
command.addHeader(ParseConstants.HEADER_SESSION_TOKEN, sessionToken);
```

As such, I'm closing this issue as it is not a bug in parse4cn1 but a change on Parse side.

**Closed by sidiabale** 2016-06-29 03:58 UTC

**Comment by Helten** [comment] 2016-06-29 07:01
Ok, thank you for looking into this

2016-06-29 5:58 GMT+02:00 Chidiebere Okwudire <notifications@github.com>:

**Comment by sidiabale** [comment] 2016-06-29 08:04
You're welcome
